### ISSUE TITLE
Problem while updating CDK deployment

### ISSUE THREAD

**Issue by cygnius** [markilott/aws-cdk-configure-ses#3]
Hi,
This code deployed well for the first time and created the SES resources as expected.
However, when I updated a few items in the same CDK app and deployed again, it gave issues saying that the resources already exist.

I looked into the CDK classes for provisioning SES resources. Now they are working fine. I rewrote the resources using standard CDK class and they are working fine.

**Comment by markilott** [comment]
Thanks for the feedback. This one is a little out of date now and as you found there are now standard CDK constructs for configuring SES.

The issue you found is due to a bug - using the index to name the resource causes problems when a list is modified:

``` js
emailList.forEach((email, i) => {
            new AwsCustomResource(this, `emailIdentity${i + 1}`, {
                // ...
            });
        });
```

If the order of the list is changed at all then it causes the CloudFormation resource name to change, and the resource may be duplicated.
